FROM arm64v8/openjdk:17
LABEL maintainer="itsupport@gmail.com"
ADD target/project-crypto-coingecko-0.0.1-SNAPSHOT.jar project-crypto-coingecko-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar","project-crypto-coingecko-0.0.1-SNAPSHOT.jar"]
EXPOSE 8085